### ISSUE TITLE
User Story 1: First Look / Landing Page

### ISSUE THREAD

**Issue by IrisHerholz** [IrisHerholz/capstone-project#1]
## Value Proposition

**As a** User
**I want to** be able to enter the country or city into the field on the landing page
**so that** i can choose the location for my journal entry.

## Description

![Bildschirmfoto 2023-01-22 um 11 29 31](https://user-images.githubusercontent.com/118169582/213911253-a55164ff-7655-4033-900d-2b70a8aab11d.png)

## Acceptance Criteria

- The landing page has a headline/title in the top of the screen
- A text element with introducing text is displayed
- One input field is displayed
- One submit button is displayed and submits the form
- The entry is displayed after the its submitted

## Tasks

- create a components folder 
- create a textfield with an appropriate description
- create a form with one text-input field and a placeholder 
- create a submit button and fix it below the input-field 
- the submit button renders the input below the button 

## Complexity

S

**Comment by RobinWitt** [comment]
Hi Iris, the complexity and scope of this story look very good to me from the beginning.

One Question would be what happens when the User enters something in both input fields?
You might want to prevent that by disabling one of the input fields or just using one input field and two radio buttons that have the option to pick either "city" or "country".

That are just two suggestions, I hope this feedback is helpful to you.

**Comment by IrisHerholz** [comment]
It is helpful and i will adjust one of the suggest! Thank you for the feedback!

**Comment by IrisHerholz** [comment]
It is helpful and i will implement one of the suggest! Thank you for the feedback!

**Comment by SaschaRadojkovic** [comment]
hi Iris , do the radio buttons have any functionality? if yes you should maybe add a Task  to handle the checkboxes to disable the unchecked input field. or something like this .. i hope my thoughts getting better in this user storys  i try to learn from reviewing others US now ;) .  and maybe you could render the input below the input field because your submit button have no function at this time :)( but how i said i only try to learn from reviewing)

**Comment by IrisHerholz** [comment]
Hello Sascha,

you are right. I need to add the task for the function of radio buttons.
Thanks, for leaving a comment and the hints :)

**Comment by ghost** [comment]
Hi Iris,
this user story seems good to me, except that i find it somehow strange to decide for 1 input field.
Normaly i think the user would like to input the country AND maybe several cities to keep track of the travel journey.
But you can decide what your app should do! 
Hope this helps you :)

**Comment by IrisHerholz** [comment]
Hey Tariq, 
I understand the irritation about the two input fields. I added specific labels to make it clearer. (They are also intended for the detailpage, but I'll add it later).
Thx for ur feedback :)

**Comment by NikRoe** [comment]
Hi Iris,

overall good user story!

I am only wondering about one point:
You mention that the submitted data will be displayed. However, you don't specify where it will be visible and in what form. This is the only thing that is missing for this user story.

Displaying data might even be a whole user story on its own. And when thinking about in which order to implement those user stories, having some dummy data displayed should come before being able to add new entries.

Hope this helps 🤞

**Comment by Long-HaHoang** [comment]
Hi Iris,

Similar what @NikRoe said, I think the scope of your story is a bit too much.

I would split the story into two and using dummy data.

You can also combine both inputs, otherwise you will need to feed your city dropdown menu with a thousands cities.

Entering a city doesn't give a country indicator. It's a big world their are multiple cities with the same name.

Furthermore some issues I found.

- We are using checkbox for Acceptance Criteria and Tasks 
- You have a typo in right menu over "Budapest" `cityies` instead of `cities`
- Is "list of countries/cities a button? If so I would move it to the next story.
- if not how about making it more visible in the picture. I mean it's not list if it's empty.
- Can you specify "text area" in your first acceptance criteria
- And it depends on you but maybe you should rise the complexity level

**Comment by IrisHerholz** [comment]
Thanks for the detailed feedback, Long-HaHoang! 
You raise good points. I will base my US on that :)

**Comment by Long-HaHoang** [comment]
Hi Iris,

As I mention before I think the scale of the first user story is too big.

Those are elements you have in the current story:
- Option to chose a field with radio buttons
- Disable field depending on radio buttons
- Two input fields type text
- Two  input fields type option
- A submit button
- A query from the inputs to display the option/ input value
- A dropdownlist without entries, therefore no function

Here is a small sketch for inspiration, maybe it will help you.
Have nice weekend.


Edit: Added a background can't see the picture in light mode.
![Travel_App_whatever_capstone_userstory(1)](https://user-images.githubusercontent.com/117607177/213786001-45299858-4319-47bb-b8b9-034c6e26ae69.png)

**Comment by IrisHerholz** [comment]
Hey Long-HaHoang! Cool review! Thx a lot! 
This is definitely good inspiration for another detail page that i am planning. I decided its better to keep the first page just simple.

**Comment by RobinWitt** [comment]
the updated user story looks good to me!
